name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/my-app:latest

      - name: Install AWS CLI
        uses: aws-actions/aws-cli-setup@v2
        with:
          version: "latest"

      - name: Install kubectl
        uses: aws-actions/kubectl-setup@v1
        with:
          version: "latest"

      - name: Create kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-cluster

      - name: Deploy to EKS
        run: kubectl apply -f k8s/prod
