name: Deploy to EC2

on:
  push:
    branches:
      - main # This can be replaced with your deployment branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 
      name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /seyi-api # replace this with your actual project directory path
            git pull origin main
            npm run start
