name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup DigitalOcean CLI
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-image-name:latest

      - name: Update Kubernetes deployment
        run: |
          doctl kubernetes cluster kubeconfig save your-k8s-cluster-name
          kubectl set image deployment/your-deployment-name your-container-name=your-dockerhub-username/your-image-name:latest
