name: Deploy to EC2

on:
  push:
    branches:
      - develop # This can be replaced with your deployment branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /seyi-api # replace this with your actual project directory path
            git pull origin main
            # if there's any build or restart service command, add here
